
install: "npm install -g grunt-cli bower coveralls && npm install"

language: node_js

sudo: false

node_js:
  - "0.12"

branches:
  only:
  - test

env:
#  - NODE_ENV=
  - NODE_ENV=testing
#  - NODE_ENV=production


